site_name: IA-UE09-Techniques Web
copyright: Copyright &copy; 2025, G.Baltus, basé sur les notes originales de F.Leclercq et de V. Martin. Tous droits réservés.


nav:
  - Acceuil: index.md
  - EU09: 00_UE09/index.md
  - Historique du web: 
    - Bref historique: 01_HistoireWeb/index.md
    - L'internet: 01_HistoireWeb/internet.md
    - Le Web: 01_HistoireWeb/web.md
    - Les Risques: 01_HistoireWeb/Risque.md
  - HTML-Base : 
    - Les langages du Web: 02_htmlBase/index.md
    - Les bases de l'HTML : 02_htmlBase/baseHtml.md
    - La structure global : 02_htmlBase/structure.md
    - Les codages : 02_htmlBase/codage.md
    - Les naviguateurs: 02_htmlBase/navigateur.md
  - HTML-Balise :
    - Découverte : 03_htmlBalise/index.md
    - Balises : 03_htmlBalise/balises.md
    - Exercices : 03_htmlBalise/exercice.md
  - HTML-Sémantique :
    - Évolution de l'HTML: 04_htmlSemantique/index.md
    - Web sémantique : 04_htmlSemantique/html.md
    - Balise sémantique : 04_htmlSemantique/baliseSemantique.md
    - Bonnes pratiques : 04_htmlSemantique/bonnePratique.md
    - Respect des standards : 04_htmlSemantique/validation.md
    - Exercices : 04_htmlSemantique/exercice.md
  - HTML-Formulaire :
    - Introduction : 05_htmlFormulaire/index.md
    - Balises : 05_htmlFormulaire/balise.md
    - Exercices : 05_htmlFormulaire/exercice.md
  - CSS-Base :
    - Introduction : 06_cssBase/index.md
    - Héritage : 06_cssBase/heritage.md
    - Liaison : 06_cssBase/liaison.md
    - Inspecteur : 06_cssBase/inspecteur.md
    - Sélecteur : 06_cssBase/selecteur.md
    - Sélecteur avancé : 06_cssBase/selecteurAvance.md
    - S'enrtainer : 06_cssBase/entrainement.md
    - Mise en forme : 06_cssBase/miseFormeTexte.md
    - Propriété en arrière plan : 06_cssBase/arrierePlan.md
    - Exercices : 06_cssBase/exercice.md
  - CSS-Boite : 
    - Bloc-inline : 07_cssBoite/index.md
    - Modèle de boite : 07_cssBoite/boite.md
    - Centrer : 07_cssBoite/centrerBloc.md
    - Display : 07_cssBoite/display.md
    - Place occupée : 07_cssBoite/placeOccupee.md
    - Exercices : 07_cssBoite/exercice.md
  - CSS-Flex :
    - Introduction : 08_cssFlex/index.md
    - Principe : 08_cssFlex/principe.md
    - Conteneur : 08_cssFlex/conteneur.md
    - Conteneur Direction : 08_cssFlex/conteneurDirection.md
    - Conteneur Wrap : 08_cssFlex/conteneurWrap.md    
    - Conteneur Justify Content : 08_cssFlex/conteneurJustifyContent.md
    - Conteneur Align Items : 08_cssFlex/conteneurAlignItems.md
    - Conteneur Align Content: 08_cssFlex/conteneurAlignContent.md
    - Enfant Flex Basis: 08_cssFlex/enfantFlexBasis.md
    - Enfant Flex Order : 08_cssFlex/enfantFlexOrder.md
    - Enfant Flex flex-grow : 08_cssFlex/enfantFlexGrow.md
    - Enfant Flex flex-shrink : 08_cssFlex/enfantFlexShrink.md
    - Enfant Flex align-self : 08_cssFlex/enfantFlexAlignSelf.md
    - Astuces : 08_cssFlex/flexAstuces.md
    - Je suis perdu : 08_cssFlex/jeSuisPerdu.md
    - Memo : 08_cssFlex/memo.md
    - Entrainement : 08_cssFlex/entrainement.md
    - Exercices : 08_cssFlex/exercice.md
  - JS-Base :
    - Introduction : 09_jsBase/index.md
    - Variables : 09_jsBase/variables.md
    - Branchement : 09_jsBase/branchement.md
    - Exercices: 09_jsBase/exercice.md
  - JS-Fonctions :
    - Fonction : 10_jsFonction/index.md
    - Mode sctrict : 10_jsFonction/strict.md
    - Exception : 10_jsFonction/exceptions.md  
    - Exercices : 10_jsFonction/exercice.md
  - JS-Tableaux : 
    - Introduction : 11_jsTableau/index.md
    - Les objets : 11_jsTableau/objet.md
    - Les collections : 11_jsTableau/collection.md
    - Exercices : 11_jsTableau/exercice.md
  - JS-DOM : 
    - Introduction : 12_jsDOM/index.md
    - Manipuler le DOM : 12_jsDOM/manipuler.md
    - Les événements : 12_jsDOM/evenement.md
    - Exemple : 12_jsDOM/exemple.md
    - Exercices : 12_jsDOM/exercice.md
  - JS-Asynchrone :
    - Introduction : 13_jsAsynchrone/index.md
    - Promesse : 13_jsAsynchrone/promesse.md
    - Async : 13_jsAsynchrone/asynch.md
    - Exercices : 13_jsAsynchrone/exercice.md
  - NodeJS-Express:
    - Introduction : 14_NodeBase/index.md
    - Installation : 14_NodeBase/installation.md
    - Express : 14_NodeBase/express.md
    - Tuto mini-site : 14_NodeBase/tuto.md
    - Exercices : 14_NodeBase/exercice.md
  - NodeJS-Formulaire :
    - Introduction : 15_NodeFormulaire/index.md
    - Récupération : 15_NodeFormulaire/recuperation.md
    - Tuto : 15_NodeFormulaire/tuto.md
    - Exercices : 15_NodeFormulaire/exercice.md
  - NodeJS-BD :
    - Introduction : 16_NodeBD/index.md
    - SQLite : 16_NodeBD/sqlite.md
    - Repository : 16_NodeBD/repository.md
    - AJAX : 16_NodeBD/ajax.md
    - Lire des données : 16_NodeBD/lireDonnees.md
    - Sauvegarder des données : 16_NodeBD/sauvegarderDonnees.md
    - Tuto : 16_NodeBD/tuto.md
    - Exercices : 16_NodeBD/exercice.md
    


theme: 
  name : material

  palette:
  # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary : blue grey
      accent : blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  logo: img/HELMo_logo.png
  favicon: img/helmoDots.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - header.autohide


  language: fr

extra_css:
  - "css/extra.css"

# Extensions
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.progressbar
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.b64
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - attr_list
  - admonition
  - pymdownx.betterem
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search