site_name: IA-UE09-Techniques Web
copyright: Copyright &copy; 2025, G.Baltus, basé sur les notes originales de F.Leclercq. Tous droits réservés.


nav:
  - Acceuil: index.md
  - EU09: 00_UE09/index.md
  - Historique du web: 
    - Bref historique: 01_HistoireWeb/index.md
    - L'internet: 01_HistoireWeb/internet.md
    - Le Web: 01_HistoireWeb/web.md
    - Les Risques: 01_HistoireWeb/Risque.md
  - Base de l'HTML : 
    - Les langages du Web: 02_htmlBase/index.md
    - Les bases de l'HTML : 02_htmlBase/baseHtml.md
    - La structure global : 02_htmlBase/structure.md
    - Les codages : 02_htmlBase/codage.md
    - Les naviguateurs: 02_htmlBase/navigateur.md
  - Balise :
    - Découverte : 03_htmlBalise/index.md
    - Balises : 03_htmlBalise/balises.md
    - Exercices : 03_htmlBalise/exercice.md
  - Sémantique :
    - Évolution de l'HTML: 04_htmlSemantique/index.md
    - Web sémantique : 04_htmlSemantique/html.md
    - Balise sémantique : 04_htmlSemantique/baliseSemantique.md
    - Bonnes pratiques : 04_htmlSemantique/bonnePratique.md
    - Respect des standards : 04_htmlSemantique/validation.md
    - Exercices : 04_htmlSemantique/exercice.md
  - Formulaire :
    - Introduction : 05_htmlFormulaire/index.md
    - Balises : 05_htmlFormulaire/balise.md
    - Exercices : 05_htmlFormulaire/exercice.md
    
theme: 
  name : material

  palette:
  # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary : blue grey
      accent : blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  logo: img/HELMo_logo.png
  favicon: img/helmoDots.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - header.autohide


  language: fr

extra_css:
  - "css/extra.css"

# Extensions
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.progressbar
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.b64
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - attr_list
  - admonition
  - pymdownx.betterem
  - md_in_html
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search